### ISSUE TITLE
Move artifacts to maven central, as jcenter is shutting down

### ISSUE THREAD

**Issue by JesusM** [didomi/Consent-String-SDK-Android#2]
As explained in https://developer.android.com/studio/build/jcenter-migration, jcenter is going to stop serving artifacts by Febrary 1, 2022. At the moment, the didomi Android SDK artifacts are correctly served from [maven](https://mvnrepository.com/artifact/io.didomi.sdk/android), but its `com.iab.gdpr_android:gdpr_android:1.0.1` dependency is still pointing to [jcenter](https://mvnrepository.com/artifact/com.iab.gdpr_android/gdpr_android).

Before the jcenter shutdown deadline comes, it'd be nice if this library artifact is moved to maven central repository.

**Comment by jawadst** [comment]
@JesusM Thanks for your report but this library is not maintained anymore as it targeted the TCFv1 which was deprecated in 2020. We have no plans to migrate to maven for this library and we do not recommend using it.

**Comment by JesusM** [comment]
@jawadst thanks for the reply, though I might have expressed myself badly 😄 . What I meant is that checking one of the Didomi SDK maven central artifacts (for example 1.32.1, stored in https://mvnrepository.com/artifact/io.didomi.sdk/android/1.32.1) I see that in the listed dependencies, it points to https://mvnrepository.com/artifact/com.iab.gdpr_android/gdpr_android/1.0.1. That dependency is only stored on jcenter, so when jcenter potentially shuts down, the didomi sdk artifact won't compile (correct me if I'm wrong) so my question was about wether moving it to maven central would be required at that point 🤔 .

**Comment by jawadst** [comment]
@JesusM Thanks for the explanation, that makes sense.
JCenter will now stay up as a read-only repository "indefinitely" (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so I don't expect any disruption in the short-term but I'll discuss with the team to remove that dependency.

**Comment by ldavin** [comment]
Hi @jawadst,

Could you please consider moving this artifact to maven central?

My app is now depending on `io.didomi.sdk:android:1.40.1`, which transitively depends on this library.
Having it not hosted on mavenCentral forces me to add jCenter as a repository.
I had previously completely removed jCenter from my build scripts because of its deprecation 😞.

Thank you

**Comment by frcouceiro** [comment]
Hello @jawadst, any plans on migrating to maven central ? Thank you

**Comment by jawadst** [comment]
@ldavin @frcouceiro 
The Didomi SDK for Android was updated to not rely on jCenter anymore in our version 1.55.0 (https://developers.didomi.io/cmp/mobile-sdk/android/versions#1.55.0-february-7-2022).
